Algoritmo "REPITA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : REPITA
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/04/2023
//treinando o repita
Var

media:inteiro

Inicio

//j <- 1
//  repita
//    escreval(j)
//    j <- j + 1
 //   ate j> 10




repita
  escreval("Digite sua média")
  leia(media)
  
ate (media >= 0) e (media <= 10)

escreval("A media final é: ", media)

Fimalgoritmo
